"""empty message

Revision ID: 58238b65319f
Revises: ffdc0a98111c
Create Date: 2022-03-04 16:16:17.215416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58238b65319f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('developerId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developerId'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('developers', 'userId',
            existing_type=sa.INTEGER(),
            nullable=True)
    op.create_foreign_key(None, 'developers', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'developers', type_='foreignkey')
    op.alter_column('developers', 'userId',
            existing_type=sa.INTEGER(),
            nullable=False)
    op.drop_table('reviews')
    # ### end Alembic commands ###
